### ISSUE TITLE
Problem with Getting Started Guide

### ISSUE THREAD

**Issue by RunAtTekky** [divy-03/Tic-Tac-Toe#3]
After forking and cloning the project.
Guide says to run the following command
`npm start`
Which doesn't work.
## Following code will be needed for it to work properly
Use the following code to install dependencies
`npm i`

**Comment by 77dipesh77** [comment]
pls assign me an issue

**Comment by RunAtTekky** [comment]
> pls assign me an issue

Refrain from using shorthand notations.

**Comment by divy-03** [comment]
Thank you Dipesh for resolving!
